### ISSUE TITLE
Limit options to current document

### ISSUE THREAD

**Issue by PRGfx** [di-unternehmer/DIU.Neos.AnchorLink#3]
From my understanding the ContentNodeAnchorLinkResolver tries to get nodes capable of anchor links below the linked document. However this only limits the results to the correct sub-tree – which might still be quite large.
Unfortunately I am not aware of a sensible approach to correctly filter the results and can't suggest a fix (except filtering for closest document to equal the link target..).

When trying out the plugin I used the grouping feature to make clear, which options are available on the linked document as a workaround:
```yaml
DIU:
  Neos:
    AnchorLink:
      group: ${q(node).closest('[instanceof Neos.Neos:Document]').property('title')}
```
